Vagrant.configure('2') do |config|
  config.vm.box       = 'ubuntu/bionic64'
  config.vm.network "public_network", bridge: "bridge0", ip: "192.168.1.201"

  # Work around https://bugs.launchpad.net/cloud-images/+bug/1829625
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.provision "shell",
    inline: "bash /vagrant/bootstrap.retcon.bash",
    privileged: false
end
