unless Vagrant.has_plugin?("vagrant-disksize")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
end

Vagrant.configure('2') do |config|

  config.vm.box       = 'ubuntu/bionic64'
  config.vm.network "public_network", bridge: "eth0", ip: "192.168.1.202"
  config.disksize.size = '20GB'

  # Work around https://bugs.launchpad.net/cloud-images/+bug/1829625
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.provision "shell",
    inline: "bash /vagrant/bootstrap.retcon.bash",
    privileged: false
end
