#! /bin/sh

### BEGIN INIT INFO
# Provides:          retcon-manager
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

set -e

APPUSER=ubuntu
APPHOME=/home/ubuntu/retcon-manager
N=/etc/init.d/retcon-manager
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

set -e

case "$1" in
  start)
        sudo -u $APPUSER sh -c ". \$HOME/.rbenv.bash; cd $APPHOME; DAEMON_ENV=development ./bin/retcon-manager start"
	;;
  stop)
        sudo -u $APPUSER sh -c ". \$HOME/.rbenv.bash; cd $APPHOME; DAEMON_ENV=development exec ./bin/retcon-manager stop"
	;;
  reload|restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
